# Generated by Django 4.2.1 on 2023-05-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('car_type', models.CharField(blank=True, max_length=255)),
                ('durability', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(max_length=255, null=True)),
                ('identification_number', models.CharField(max_length=50)),
                ('recoding_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisLevelCrossing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_file_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='REQUEST', max_length=50)),
                ('images', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
