# Generated by Django 4.2.1 on 2023-05-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_rename_identification_number_analysisfile_road_surface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfile',
            name='area',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
