# Generated by Django 4.2.1 on 2023-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysisfile_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfile',
            name='test_count',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
