# Generated by Django 4.2.1 on 2023-05-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysisfile_test_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysislevelcrossing',
            name='chart_data',
            field=models.TextField(null=True),
        ),
    ]
