# Generated by Django 4.2.1 on 2023-05-24 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_analysislevelcrossing_chart_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysislevelcrossing',
            name='images',
        ),
        migrations.AddField(
            model_name='analysislevelcrossing',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=2048),
            preserve_default=False,
        ),
    ]
