# Generated by Django 4.2.1 on 2023-05-24 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_alter_analysislevelcrossing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysislevelcrossing',
            old_name='name',
            new_name='title',
        ),
    ]
