# Generated by Django 4.2.1 on 2023-05-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_analysislevelcrossing_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysislevelcrossing',
            name='title',
        ),
    ]
