# Generated by Django 4.2.1 on 2023-05-25 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_remove_analysislevelcrossing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysislevelcrossing',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
