# Generated by Django 4.2.1 on 2023-06-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_analysisfile_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysislevelcrossing',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
    ]
