# Generated by Django 4.2.1 on 2023-08-07 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_analysislevelcrossing_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfile',
            name='xc_split_range',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
