# Generated by Django 4.2.1 on 2023-08-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_analysisfile_xc_split_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysislevelcrossing',
            name='end_pos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='analysislevelcrossing',
            name='start_pos',
            field=models.IntegerField(null=True),
        ),
    ]
