# Generated by Django 4.2.1 on 2023-08-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_analysislevelcrossing_end_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfile',
            name='chart_cell_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
